apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ip48n8967-python
  janus-idp.io/tekton: ip48n8967-python
  backstage.io/kubernetes-id: ip48n8967-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ip48n8967-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
