apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ip48n8967-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ip48n8967-python 
  name: ip48n8967-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ip48n8967-python 
